// I know this is highly inefficient and that CSS is the correct approach.
// This is more of a learning process / experiment.



// CREATED HTML ELEMENTS

//title (which is an image)
let title                = document.createElement('img');
title.src                = "imgs/title.png";

//Sub heading
let subHeading           = document.createElement('h3');
let subHeadingText       = document.createElement('span');
subHeadingText.innerText = "This enitre page was made with JavaScript - no HTML / no CSS";
subHeading.appendChild(subHeadingText);

//content container
let container = document.createElement('div');

//first paragraph
let firstParagraph           = document.createElement('p');
firstParagraph.innerHTML     = '<span>JavaScript </span>is a client side, high level programming language. It is used in conjucture with HTML & CSS to make interactive websites. ';
//second paragraph
let secondParagraph          = document.createElement('p');
secondParagraph.innerHTML    = '<span>So what can you do with JavaScript? </span>There are many different things that you can do with JavaScript, Animations can be implemented using JavaScript using different interaction such as Hover. Or whenever the user Clicks on something. Styling can also be changed using JavaScript. You can change different colours, or Font Styles.';

//main section
let mainSection              = document.createElement('section')



// STYLING

//General styling

document.body.style.fontFamily     = 'Raleway';
document.body.style.color          = 'white';
document.body.style.background     = 'linear-gradient(259.81deg, #E8FF5A 5.72%, #70FFDD 83.31%)';
document.body.style.fontSize       = '20px';

//section styling
mainSection.style.width            = '90%';
mainSection.style.height           = '2000px';
mainSection.style.margin           = '40px auto'
mainSection.style.backgroundColor  = '#353535';
mainSection.style.display          = 'flex';
mainSection.style.flexDirection    = 'column';
mainSection.style.alignItems       = 'center';
//Container styling
container.style.width              = '70%';
container.style.display            = 'flex';
container.style.flexDirection      = 'column';
container.style.alignItems         = 'center';
//title
title.style.width                  = '400px';
title.style.height                 = 'auto';
title.style.margin                 = '130px auto 0';
//h3 styling 
subHeading.style.fontSize          = '12px';
subHeading.style.letterSpacing     = '1px';
subHeading.style.fontWeight        = 'lighter';
subHeading.style.color             = '#C5C5C5';
subHeading.style.textAlign         = 'center';
subHeading.style.margin            = '40px auto';
//First paragraph styling
firstParagraph.style.marginTop     = '150px';
firstParagraph.style.lineHeight    = '40px';
//Second paragraph styling      
secondParagraph.style.lineHeight   = '40px';
secondParagraph.style.marginTop    = '100px';


//Add created Elemements to HTML, add created elements to section first.
container.appendChild(title);
container.appendChild(subHeading);
container.appendChild(firstParagraph);
container.appendChild(secondParagraph);
mainSection.appendChild(container);
document.body.appendChild(mainSection);

//Selecting different elements once they have been generated by JS.
var span = document.querySelectorAll('span');

//change the property of the first span
span[1].style.color = '#70FFDD';
span[1].style.fontSize = '40px';
//change the property of the second span
span[2].style.color = '#70FFDD';
span[2].style.fontSize = '40px';











